# application configuration

application.name: 'platform-core'
info.app:
  version: '4.1.5'
  description: 'Composable application core library'

# server port for Event API REST endpoint
server.port: 8300

#
# log.format = text | compact | json
# text and json are for human readers
# compact is json without pretty print. It is for log analytics consumption.
#
log:
  format: text
  level: INFO

# You can add optional health checks that point to your custom health check functions
# (the dependency list is a comma separated list) 
# health.dependencies: 'demo.health'

#
# Static HTML folder location - default to "resources/public" of the mercury library if not given.
# static.html.folder: '/opt/html'
